### ISSUE TITLE
Wrong job listing in Company Profile page

### ISSUE THREAD

**Issue by 3mounika** [iamgabrielma/WPJM-Company-Profile-Page#13]
Hello, plugin is not working. When I open single company profile page. The jobs links are wrong. When you click on job it goes to another job. Try to add 2 or 3 jobs and different companies and check it you will know.

Check the below image.
![rnsj60](https://user-images.githubusercontent.com/10848625/50130584-452d4e80-02a4-11e9-8abf-ab7669eaeff9.jpg)

**Comment by iamgabrielma** [comment]
I wasn't able to replicate the issue you're seeing. Can you provide more information about how have you setup your listings under `Job Listings > Companies` for that specific job? A few screenshots of your back-end setup will help as well.

I also see in the bottom of your screenshot the URL shows a `-2`, this normally means you have another job with the exact same slug, be sure you're not editing former listings with a different setup.
