### ISSUE TITLE
Company Page not Created

### ISSUE THREAD

**Issue by chronicinternet** [iamgabrielma/WPJM-Company-Profile-Page#17]
When the plugin was activated, the "company" page under pages was not created. Is there a short code? or how do I create a company page?

**Comment by iamgabrielma** [comment]
> the "company" page under pages was not created. Is there a short code? or how do I create a company page?

Company pages will be created automatically by clicking in the company name, under any of your listings. Can you provide an URL where this can be seen?

Also can you try to flush your permalinks? Under wp-admin > Settings > Permalinks , just click on `save` again with any modification, then refresh the company page and see if now appears.
