### ISSUE TITLE
plugin not compatible anymore ?

### ISSUE THREAD

**Issue by joblux** [iamgabrielma/WPJM-Company-Profile-Page#18]
is this addon abandonned or does it work with todays version still ?

**Comment by iamgabrielma** [comment]
Hi @joblux , I found and fixed an issue in the last release. Please update the plugin and let me know if you're seeing any problem.

For future reference, please add as maximum details as possible when reporting a problem.

**Comment by joblux** [comment]
how do i set up shotcode for companies page ?

**Comment by AmineBAIK1** [comment]
Hello,
Thanks for the newupdate,
I was looking to how to set up this plugin then i used this URL
https://tilcode.blog/wpjm-company-profile-page-add-a-company-profile-page/
in the text its written “you will see a new meta-box to the right side, titled “Companies”.
I just dont see it at all, it doesnt exist for me..

**Comment by iamgabrielma** [comment]
Hi @AmineBAIK1  , this seems to be a problem with the latest editor, I opened an issue here: https://github.com/iamgabrielma/WPJM-Company-Profile-Page/issues/20 to fix it as soon as possible.

For the moment a workaround is to enable the classic editor installing and activating https://wordpress.org/plugins/classic-editor/ , then you'll see the metabox within the edit page. Once you have added the info the classic editor can be disabled if you wish to.

A fix will come soon!
